#' Index number formulas (economic statistics notes)
#' @param topic optional, one or more of: "problems", "basics", "relatives", "weights",
#'   "properties", "emerging", "tests", "chain", "errors", "indices", "uses",
#'   "lorenz", "inequality", "pareto".
#'   NULL lists all.
#' @export
ecoformulas <- function(topic = NULL) {
  f <- list(
    problems = c(
      "PROBLEMS IN CONSTRUCTING INDEX NUMBERS",
      "  1. Purpose      : state it unambiguously (CLI = household expenditure, WPI = wholesale prices)",
      "  2. Base period  : price level of BP taken as 100; CP expressed relative to it. BP should be",
      "       (i) normal, recent (no war/pandemic/recession); (ii) not too distant (commodities appear/disappear);",
      "       (iii) neither too short nor too long; (iv) reliable figures available, preferably economically important",
      "  3. Selection of commodities : representative of consumer expenditure, commonly used, cover all major goods",
      "       (CLI excluding petrol under-estimates inflation when fuel rises); judgement sampling, NOT random sampling",
      "  4. Collection of data : price quotations from several representative markets;",
      "       retail prices for CLI, wholesale prices for WPI",
      "  5. Combining data : distribution of price relatives is bell-shaped with central tendency (BP in recent",
      "       past) -> use AM/GM/HM of PRs, or simple/weighted aggregates (see 'relatives')",
      "  6. Choice of weights : commodities differ in importance (see 'weights')",
      "  7. Interpretation : WPI = change in general price level BP -> CP;",
      "       CLI = money needed to buy the same basket in both periods"),
    basics = c(
      "BASICS  (Index Number notes)",
      "  Notation : BP = base period '0' (price p0, qty q0);  CP = current period '1' (price p1, qty q1)",
      "  Actual change = p1 - p0 ;  Relative change = p1/p0  (preferred)",
      "  Price relative (PR) of item i = p1i/p0i ;  Quantity relative = q1i/q0i",
      "  Binary commodities = present in both periods ;  unique = present in only one",
      "  BP has k commodities, CP has l, m binary  ->  unique = k + l - 2m",
      "  BP level is taken as 100; CP is expressed relative to it",
      "  Swap p and q everywhere to turn a price index (PIN) into a quantity index (QIN)"),
    relatives = c(
      "COMBINING DATA: central tendency of price relatives (n commodities)",
      "  Unweighted, using PRs :",
      "    AM : (1/n)*sum(p1i/p0i)",
      "    GM : ( prod(p1i/p0i) )^(1/n)",
      "    HM : n / sum(p0i/p1i)",
      "  Simple aggregated index (SAI) : sum(p1i) / sum(p0i)",
      "  Weighted aggregated index (WAI) : sum(p1i*wi) / sum(p0i*wi)",
      "    with wi = 1/p0i, WAI = AM of PRs",
      "  Weighted PRs :",
      "    AM : sum( (p1i/p0i)*wi ) / sum(wi)",
      "    GM : ( prod( (p1i/p0i)^wi ) )^(1/sum(wi))",
      "    HM : sum(wi) / sum( (p0i/p1i)*wi )"),
    weights = c(
      "CHOICE OF WEIGHTS (price index; for a quantity index swap p and q)",
      "  Laspeyres (1871) : wi = q0i  (base year qty)",
      "    I01^L = sum(p1i*q0i) / sum(p0i*q0i)",
      "  Paasche          : wi = q1i  (current year qty)",
      "    I01^P = sum(p1i*q1i) / sum(p0i*q1i)",
      "  Quantity index versions: wi = p0i (Laspeyres), wi = p1i (Paasche)",
      "  Laspeyres: basket fixed, cheaper to collect (base qty usually recorded), shows price change alone;",
      "             ignores substitution effect -> upward bias",
      "  Paasche  : basket changes each period (price mixed with qty change), harder to collect in real time;",
      "             reflects substitution -> downward bias",
      "  Value index : V = I_V = sum(p1i*q1i) / sum(p0i*q0i)"),
    properties = c(
      "LASPEYRES vs PAASCHE",
      "  Constant price proportion p1i = k*p0i for all i : I^L = I^P = k",
      "  Constant quantity proportion q1i = k*q0i for all i : I^P = I^L",
      "  Proof that L >= P (exam):",
      "    xi = p1i/p0i, yi = q1i/q0i, wi = p0i*q0i  (weighted)",
      "    sx*sy*r_xy = sum(wi*xi*yi)/sum(wi) - sum(wi*xi)*sum(wi*yi)/(sum(wi))^2",
      "               = sum(p1i*q1i)/sum(p0i*q0i) - [sum(p1i*q0i)/sum(p0i*q0i)]*[sum(p0i*q1i)/sum(p0i*q0i)]",
      "               = V - I^L * V / I^P = V*(1 - I^L/I^P),   V = value index",
      "    Normal economic conditions (demand function): r_xy < 0, V > 0, sx > 0, sy > 0",
      "      => 1 - I^L/I^P < 0  =>  I^L >= I^P",
      "  Special cases: r_xy = 0 -> I^L = I^P ;  sx = 0 and sy = 0 -> I^L = I^P",
      "  Rising market: Laspeyres shows higher price;  falling market: Paasche shows greater fall"),
    emerging = c(
      "FORMULAE BASED ON LASPEYRES AND PAASCHE",
      "  Edgeworth-Marshall : wi = (q0i + q1i)/2   [AM of L and P weights]",
      "    I^ME = sum(p1i*(q0i + q1i)) / sum(p0i*(q0i + q1i))",
      "  Walsh              : wi = sqrt(q0i*q1i)   [GM of L and P weights]",
      "    I^W  = sum(p1i*sqrt(q0i*q1i)) / sum(p0i*sqrt(q0i*q1i))",
      "  Bowley             : I^B = (I^L + I^P)/2    [AM of L and P indices]",
      "  Fisher             : I^F = sqrt(I^L * I^P)  [GM of L and P indices]",
      "  Kelly              : wi = q_alpha,i, alpha = hypothetical time point between 0 (BP) and 1 (CP), usually midpoint",
      "",
      "Show I^ME and I^F lie in [I^P, I^L]  (i.e. between the two)",
      "  Let a = sum(p1i*q0i), b = sum(p0i*q0i), c = sum(p1i*q1i), d = sum(p0i*q1i)",
      "  I^L = a/b, I^P = c/d, I^ME = (a+c)/(b+d)",
      "  (1) I^ME = l1*I^L + l2*I^P with l1 = (1/b)/((1/b)+(1/d)), l2 = (1/d)/((1/b)+(1/d)),",
      "      l1 + l2 = 1, 0 <= l1,l2 <= 1  -> convex combination, so lies between I^L and I^P",
      "      Alternate: a/b <= c/d  =>  a/b <= (a+c)/(b+d) <= c/d   for a,b,c,d > 0",
      "        (ad <= bc ; add ab: a(b+d) <= b(a+c) ; add cd: d(a+c) <= c(b+d))",
      "  (2) If I^L >= I^P: (I^L)^2 >= I^L*I^P  => I^L >= sqrt(I^L*I^P) = I^F",
      "                      I^L*I^P >= (I^P)^2 => I^F >= I^P   so I^F in [I^P, I^L]"),
    tests = c(
      "TESTS FOR INDEX NUMBERS",
      "  1. Identity        : I00 = 1   (e.g. I00^L = sum(p0i*q0i)/sum(p0i*q0i) = 1)",
      "  2. Unit            : index independent of the units of price and quantity",
      "  3. Proportionality : if p1i = k*p0i for all i then I01 = k   (e.g. Laspeyres gives k)",
      "  4. Time reversal (Fisher) : I01 * I10 = 1",
      "       Fail : Laspeyres, Paasche, HM(PR)",
      "       Pass : ME, Fisher, GM(PR)   (these three are the ones worked in the notes)",
      "       [not in notes, derived: Walsh and Kelly (fixed weights) also pass; Bowley fails]",
      "       ME check: [sum(p1(q0+q1))/sum(p0(q0+q1))] * [sum(p0(q0+q1))/sum(p1(q0+q1))] = 1",
      "       GM(PR) check: (prod(p1/p0))^(1/n) * (prod(p0/p1))^(1/n) = 1",
      "  5. Factor reversal (Fisher) : Ip * Iq = Iv   (Iv = sum(p1q1)/sum(p0q0), swap p and q to get Iq)",
      "       Fail : ME, GM(PR)  (GM gives (prod(p1q1/(p0q0)))^(1/n) != Iv)",
      "       Pass : Fisher   [Ip*Iq = sqrt(Lp*Pp*Lq*Pq) = sum(p1q1)/sum(p0q0)]",
      "       Only Fisher satisfies both time and factor reversal -> 'ideal index number'",
      "  6. Circular test : I01 * I12 * ... * I(n-1)n * In0 = 1   (time reversal is a special case)",
      "       Fail : Laspeyres, Paasche, Fisher, ME, HM(PR), AM(PR)",
      "       Pass : GM(PR)   [circular yes, time reversal yes, factor reversal no]"),
    chain = c(
      "CHAIN INDEX",
      "  Link indices : I01, I12, ..., I(n-1)n   (previous period as base)",
      "  Chain indices: I'01 = I01 ;  I'02 = I01*I12 ;  ... ;  I'0n = I01*I12*...*I(n-1)n",
      "  I(k-1)k is the fixed base index of period k w.r.t. base k-1",
      "  Chain = fixed base index only if the formula meets the circular test",
      "  Merits of chain over fixed base:",
      "    (i)  fixed base becomes inaccurate as BP and CP drift apart; chain is better for long term",
      "    (ii) chain uses information of all intervening periods; fixed base uses only BP and CP",
      "  Demerits:",
      "    (i)  fixed base is easier to calculate and understand",
      "    (ii) chain multiplies links -> cumulative error"),
    errors = c(
      "ERRORS IN INDEX NUMBERS  (formula, sampling, homogeneity)",
      "  1. Formula error : no universally accepted formula",
      "       D(p) = I01^L - I01^P ;  D = 0 <=> I^L = I^P  (q0i and q1i do not differ much on average)",
      "       D small -> Laspeyres, Paasche or any cross accepted; take two nearby periods to keep D small",
      "       Joint error if tests fail:",
      "         Time reversal   : E = I01*I10 - 1",
      "         Factor reversal : E = (Ip*Iq)/Iv - 1",
      "  2. Sampling error : formula uses n items rather than N",
      "       |P01(N) - P01(n)|  or  |Q01(N) - Q01(n)|   (N, n = binary commodities in population, sample)",
      "       decreases as n grows, varies inversely with sqrt(n), vanishes if all binary commodities included",
      "  3. Homogeneity error : index uses binary commodities instead of all commodities in BP and CP",
      "       |P01(T) - P01(N)|  or  |Q01(T) - Q01(N)|   (T = all commodities, binary + unique)",
      "       no direct measure; indirect measure:",
      "         R = (unique commodities in periods 0 and 1) / (all commodities in periods 0 and 1)",
      "           = ((N0 - N01) + (N1 - N01)) / (N0 + N1) = (N0 + N1 - 2*N01)/(N0 + N1)",
      "         N0, N1 = commodities in BP, CP;  N01 = binary commodities",
      "         (notes call N0, N1 'unique', but the formula only works if they are the BP/CP totals)",
      "       0 <= R <= 1 ; R = 0 complete homogeneity, R = 1 complete heterogeneity",
      "       R -> 0 : P01(T) ~ P01(N), Q01(T) ~ Q01(N)"),
    indices = c(
      "IMPORTANT INDICES (India)",
      "  CLIN (cost of living)  : published monthly by Labour Bureau of India",
      "  WPIN (wholesale price) : published by Office of Economic Adviser of India",
      "  IIP (industrial prod.) : published by CSO under MOSPI",
      "",
      "COST OF LIVING INDEX NUMBER (CLIN)",
      "  Measures average change in money needed for equivalent satisfaction; relates to a designated group",
      "  CLIN = 135 -> cost up 35% vs base year; family spending Rs 50,000 in BP now needs 50000 * 1.35 = Rs 67,500",
      "  Steps (middle class, Kolkata):",
      "    1. specify class of people (homogeneous in income) and geographic region",
      "    2. family budget enquiry in a normal period: nature, quality, qty of commodities under five heads",
      "       (Food, Clothing, Fuel & Lighting, House Rent, Miscellaneous); proportion of expenditure per item",
      "       within group and per group within total",
      "    3. retail price quotations from the localities where the class resides",
      "    4. compute a separate index per group and a general index:",
      "       (i)  Weighted aggregated method : group index = Laspeyres = sum(p1i*q0i)/sum(p0i*q0i)",
      "       (ii) Family budget method       : group index = sum(wi*Pi)/sum(wi),",
      "                                         wi = p0i*q0i, Pi = p1i/p0i",
      "       General index = weighted average of group indices (weights = group expenditure):",
      "         CLIN = sum(I*W) / sum(W)",
      "  Extra allowance to keep BP standard of living:",
      "    100 in BP = CLIN in CP, so salary_BP * CLIN/100 = salary needed in CP",
      "    allowance = salary_BP * CLIN/100 - salary_CP",
      "    (example: 450 * 630/100 = 2835 ; 2835 - 2000 = Rs 835 more)",
      "  Worked data (Fundamentals of Statistics p.397; CLIN = 630 given, 1988 vs base 1960, Calcutta):",
      "    group (index, weight): Food (731.4, 54.31), Clothing (538.1, 7.36), House Rent (178.7, 10.5),",
      "                           Fuel & Lighting (1025.4, 4.91), Misc (540.1, 22.92)",
      "    check: sum(I*W)/sum(W) = 629.73 ~ 630 (weights sum to 100)"),
    uses = c(
      "APPLICATIONS OF CLIN: purchasing power, real income, deflation",
      "  Purchasing power of money (PP) = 100 / CLIN   (varies inversely with the price level)",
      "    price level up -> PP down (inflation);  price level down -> PP up (deflation)",
      "    PP = 0.66 : Re 1 today buys what about 66 paise bought in the base year",
      "    example: CLIN(2026; base 2020) = 160 -> PP = 100/160 = 0.625 = 62.5%; PP fell by 100 - 62.5 = 37.5%",
      "             Rs 100 in 2026 buys what Rs 62.50 bought in 2020",
      "  Real income = (Nominal income / CLIN) * 100",
      "    nominal income asks 'how much money do I receive?'; real income asks 'what can that money buy?'",
      "    example: Rs 40,000 (2020) -> Rs 60,000 (2026), CLIN = 150",
      "      nominal rise = (60000 - 40000)/40000 * 100 = 50%;  PP = 100/150 = 0.667",
      "      real income = 60000 * 100/150 = Rs 40,000 at 2020 prices -> real income unchanged",
      "      a rise in salary does not necessarily mean a rise in standard of living",
      "  Deflation = removing the effect of price changes to study real value / real income",
      "    Real (deflated) value = (Nominal value / Price index) * 100   [price index acts as the deflator]",
      "    nominal value can rise because quantity rose, prices rose, or both; deflating isolates the real change",
      "    index 150 means current prices are 50% above base; this is a statistical adjustment, not falling prices"),
    lorenz = c(
      "LORENZ CURVE (curve of concentration; measure of inequality of income/wealth, Lorenz)",
      "  N = total frequency, I = total income",
      "  F(x)   = (no. of persons with income <= x) / N * 100                  cumulative % of persons",
      "  Phi(x) = (total income of persons with income <= x) / I * 100         cumulative % of income",
      "  F and Phi run from 0 to 100; Lorenz curve = plot of Phi(x) against F(x)",
      "  Line of equality (LOE): Phi = F  (p% of persons receive p% of income)",
      "  Phi <= F always -> curve lies below LOE (slope starts small, rises as we reach richer groups)",
      "    e.g. (20% persons, 80% income) is not possible: the poorest 20% cannot hold more than 20%",
      "  Area of concentration (Lorenz area, LA) = area between LOE and curve; larger area = more concentration",
      "  Use: compare how inequality changed over time or between two countries.",
      "    curve nearer the LOE throughout -> less inequality;  if two curves intersect, larger area -> more inequality",
      "",
      "COMPUTATION FROM GROUPED DATA (n income classes)",
      "  f_i = persons in class i, I_i = income of class i, N = sum(f_i), I = sum(I_i)",
      "  p_i = f_i/N  (population share),   x_i = I_i/I  (income share)",
      "  y_i = p_1 + ... + p_i  (cumulative population share, y_0 = 0)",
      "  z_i = x_1 + ... + x_i  (cumulative income share,     z_0 = 0)",
      "  Area of triangle OAB = 1/2",
      "  Area under Lorenz curve (trapezia) = (1/2) * sum_{i=1..n} (z_i + z_(i-1)) * p_i      (z_0 = 0)",
      "  Lorenz area LA = 1/2 - (1/2)*sum(z_i + z_(i-1))*p_i = (1/2)*[1 - sum_{i=1..n} (z_i + z_(i-1))*p_i]",
      "  Lorenz ratio (concentration ratio) = LA / (1/2) = 2*LA = 1 - sum_{i=1..n} p_i*(z_i + z_(i-1)) = G",
      "  This is the Gini coefficient G;  larger G = greater inequality",
      "",
      "GINI FROM RAW DATA  (y_i = income of person i, n persons, ybar = mean income)",
      "  G = (1 / (2*n^2*ybar)) * sum_i sum_j |y_i - y_j|",
      "  Perfect equality : G = 0",
      "  Perfect inequality (one person gets everything): G = 2n(n-1)*ybar/(2*n^2*ybar) = (n-1)/n",
      "  0 <= G < 1",
      "  Assignment: equivalent forms, with y_1 <= y_2 <= ... <= y_n",
      "    G = (2/(n^2*ybar)) * sum_i (i - (n+1)/2) * y_i                  [weighted average form]",
      "    G = 1 + 1/n - (2/(n^2*ybar)) * sum_i (n+1-i) * y_i              [ranks reversed: poorest gets rank n]",
      "",
      "R CODE  (packages: ineq; reldist only for unequal class sizes)",
      "  library(ineq); library(reldist)",
      "  Equal groups (e.g. deciles), x = income shares:",
      "    plot(Lc(x)); lines(Lc(x2))        # Lorenz curve; lines() overlays a second curve",
      "    Gini(x)                           # Lorenz ratio G",
      "    Gini(x)/2                         # area of concentration LA  (G = 2*LA)",
      "  Unequal groups, hh = % of households, inc = % of income:",
      "    plot(Lc(inc/hh, n = hh))          # inc/hh = income per household, n = group sizes",
      "    gini(inc/hh, weights = hh)        # G ;  divide by 2 for LA"),
    inequality = c(
      "OTHER MEASURES OF INEQUALITY  (y_i, i = 1..n, mean ybar)",
      "  1. Relative range           : R = (max y_i - min y_i) / ybar",
      "  2. Relative mean deviation  : M = sum|y_i - ybar| / (n*ybar)",
      "  3. Gini coefficient         : G = (1/(2*n^2*ybar)) * sum_i sum_j |y_i - y_j|",
      "  4. Variance                 : V = (1/n)*sum(y_i - ybar)^2",
      "  5. Coefficient of variation : C = (sqrt(V)/ybar) * 100%",
      "  All are non-negative; except the variance they measure relative inequality, i.e. invariant to any",
      "  proportional change of all incomes.",
      "  Case 1  Perfect equality (everyone gets the same proportion): R = M = V = G = 0",
      "  Case 2  Perfect inequality (all income to one person, y_1 = n*ybar, rest 0):",
      "    G = (n-1)/n ;  R = n ;  M = 2(n-1)/n = 2G ;  V = ybar^2 * (n-1) ;  C = sqrt(n-1)"),
    pareto = c(
      "PARETO DISTRIBUTION (simulating / graduating income distributions)",
      "  Positively skewed, no hump, long right tail: models incomes beyond the modal point;",
      "  few people hold a large share of income (80-20 rule: about 20% of people hold 80% of wealth)",
      "  P_x = proportion of persons with income x or more = A*x^(-alpha),   alpha > 0 (shape)",
      "    ln P_x = ln A - alpha*ln x : log of proportion varies inversely with log of income (power law)",
      "  x0 = minimum income: P_(x0) = 1  =>  A = x0^alpha",
      "    P_x = (x0/x)^alpha,   x >= x0, alpha > 0",
      "    1 - F(x) = (x0/x)^alpha",
      "    f(x) = alpha * x0^alpha / x^(alpha+1),   x >= x0, alpha > 0",
      "  Mean income: Ybar = E(X) = integral_{x0..inf} t*f(t) dt = alpha*x0/(alpha-1),   alpha > 1",
      "",
      "LORENZ CURVE OF THE PARETO DISTRIBUTION",
      "  q_x = 1 - P_x   (proportion of persons with income x or less)",
      "  Y_x = income held by persons with income >= x = integral_{x..inf} t*f(t) dt = alpha*x0^alpha / ((alpha-1)*x^(alpha-1))",
      "  y_x = proportion of income held by the lower q_x = (Y - Y_x)/Y = 1 - Y_x/Y",
      "      = 1 - (x0/x)^(alpha-1) = 1 - (P_x)^((alpha-1)/alpha)",
      "  Lorenz curve :  L(q) = 1 - (1 - q)^((alpha-1)/alpha),   alpha > 1",
      "",
      "GINI COEFFICIENT FROM PARETO",
      "  G = 2 * [ 1/2 - integral_{0..1} (1 - (1-q)^((alpha-1)/alpha)) dq ] = 1 / (2*alpha - 1)",
      "    (integral of (1-q)^((alpha-1)/alpha) over 0..1 = alpha/(2*alpha-1))",
      "  As alpha increases, G decreases (less inequality)")
  )
  if (!is.null(topic)) {
    topic <- tolower(topic)
    bad <- setdiff(topic, names(f))
    if (length(bad))
      warning("unknown topic(s): ", paste(bad, collapse = ", "),
              ". Choose from: ", paste(names(f), collapse = ", "), call. = FALSE)
    f <- f[intersect(topic, names(f))]
  }
  for (x in f) writeLines(c(x, ""))
  invisible(f)
}
